// CH-10-Vue_Todo/VueClient/grpctodo/src/components/Todo.vue
<template>
  <div  >
    <h3>TODO gRPC Client</h3>
    <table style="border:1px">
      <tr >
        <th>
          <input
            v-model="inputField"
            v-on:keyup.enter="addTodo"
            class=""
            placeholder="Todo Item"
          />
        </th>
        <th>
          <button @click="addTodo" class="btn btn-primary">Add Todo</button>
        </th>
      </tr>

      <tr v-for="todo in todos" v-bind:key="todo.id">
        <td>
          <span>{{ todo.task }}</span>
        </td>
        <td>
          <button @click="deleteTodo(todo)" class="btn-danger">DELETE</button>
        </td>
      </tr>
    </table>
  </div>
</template>

<script>
import { Todo, Empty, TodoId } from "../protos/todo_pb";
import todoService from "../protos/todo_grpc_web_pb";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";

export default {
  data: function () {
    return {
      inputField: "",
      todos: [],
    };
  },
 
  methods: {
    getTodos: function () {
      let getRequest = new Empty();
      this.client.getAll(getRequest, {}, (err, response) => {
        this.todos = response.toObject().todosList;
        console.log(this.todos);
      });
    },
    addTodo: function () {
      let request = new Todo();
      request.setTask(this.inputField);
      this.client.insert(request, {}, () => {
        this.inputField = "";
        this.getTodos();
      });
    },
    deleteTodo: function (todo) {
      let deleteRequest = new TodoId();
      deleteRequest.setId(todo.id);
      this.client.delete(deleteRequest, {}, (err, response) => {
        if (response.getMessage() === "success") {
          this.getTodos();
        }
      });
      console.log("todo -> ", todo.id);
    },
  },
  mounted() {
    this.client = new todoService.TodoServiceClient("https://localhost:5001");
    this.getTodos();
  },
};
</script>

// CH-11-Angular_Todo/AngularClient/grpctodo/src/app/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoServiceClient } from '../../protos/TodoServiceClientPb';
import * as grpcWeb from 'grpc-web';

import {
  DeleteResponse,
  Empty,
  Todo as gtodo,
  TodoId,
  TodoList,
} from '../../protos/todo_pb';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css'],
})
export class TodoComponent implements OnInit {
  client: TodoServiceClient;
  todo: Todo = new Todo();
  todos: Todo[] = [];
  inputField: '' = '';

  constructor() {
    this.client = new TodoServiceClient('https://localhost:5001');
  }

  ngOnInit(): void {
    this.getTodos();
  }

  getTodos() {
    let getRequest = new Empty();
    this.client.getAll(
      getRequest,
      {},
      (err: grpcWeb.Error, response: TodoList) => {
        var result = response.toObject();
        console.log(result);
        this.todos = response.toObject().todosList;
        console.log(this.todos);
      }
    );
  }
  addTodo() {
    let request = new gtodo();
    request.setTask(this.inputField);
    this.client.insert(request, {}, (err: grpcWeb.Error, response: gtodo) => {
      console.log(response.toObject());

      this.inputField = '';
      this.getTodos();
    });
  }
  deleteTodo(todo: any) {
    let deleteRequest = new TodoId();
    deleteRequest.setId(todo.id);
    this.client.delete(
      deleteRequest,
      {},
      (err: grpcWeb.Error, response: DeleteResponse) => {
        if (response.getMessage() === 'success') {
          this.getTodos();
        }
      }
    );
    console.log('todo -> ', todo.id);
  }
}

class Todo {
  id!: string;
  task!: string;
}

<div>
  <h3 style="text-align: center;">TODO gRPC Client</h3>
  <table style="text-align: center;margin-left: 10px;">
    <tr>
      <th>
         <input [(ngModel)]="inputField" class="mr-1" placeholder="Todo Item">
      </th>
      <th>
        <button (click)="addTodo()" class="btn btn-primary">Add Todo</button>
      </th>
    </tr>
    <tr *ngFor="let todo of todos">
      <td>
        <span>{{todo.task}}</span>
      </td>
      <td>
        <button (click)="deleteTodo(todo)" class="btn-danger"> DELETE </button>
      </td>
    </tr>
  </table>
</div>
